### ISSUE TITLE
support 4.1

### ISSUE THREAD

**Issue by gquintard** [xcir/libvmod-parseform#2]
Hi!

It seems that 4.1 support (which is still supported) is only one commit away: https://github.com/gquintard/libvmod-parseform/commit/ce6d5f6dff76b69dc9ee4bd7c73d468af79e01f4

I would have proposed a PR, but you don't have a 4.1 branch :-)

Let me know if you want to bring that in, otherwise I'll keep my own copy.

Cheers,

**Comment by xcir** [comment]
Thanks!
I thought that 4.1.x would be EOL at latest release.
But, 4.1.x is supported :)
I created varnish41 branch.
Would you please open a PR?

**Comment by gquintard** [comment]
done with #3
